export const origin_bldgscore_table = [
  {
    bldgName: "empty",
    landscapeValue: 0.5,
    businessValue: 0.5,
    publicValue: 0.5,
    minus: [],
    modelType: "empty",
  },
  {
    bldgName: "house",
    landscapeValue: 5,
    businessValue: 2.5,
    publicValue: 0,
    minus: ["north"],
    modelType: "normal",
  },
  {
    bldgName: "workspace",
    landscapeValue: 3.5,
    businessValue: 3,
    publicValue: 0.5,
    minus: ["south"],
    modelType: "normal",
  },
  {
    bldgName: "retail",
    landscapeValue: 4.5,
    businessValue: 2.5,
    publicValue: 1.0,
    minus: [],
    modelType: "normal",
  },
  {
    bldgName: "amenities",
    landscapeValue: 4,
    businessValue: 2,
    publicValue: 1.5,
    minus: [],
    modelType: "normal",
  },
  {
    bldgName: "solarPanel",
    landscapeValue: 1.5,
    businessValue: 2.0,
    publicValue: 3.0,
    minus: ["north"],
    modelType: "normal",
  },
  {
    bldgName: "greenhouse",
    landscapeValue: 4,
    businessValue: 1,
    publicValue: 4.5,
    minus: [],
    modelType: "normal",
  },
  {
    bldgName: "windFarm",
    landscapeValue: 2,
    businessValue: 1.5,
    publicValue: 3,
    minus: ["low"],
    modelType: "normal",
  },
  {
    bldgName: "waterTank",
    landscapeValue: 4,
    businessValue: 0.5,
    publicValue: 3,
    minus: [],
    modelType: "normal",
  },
  {
    bldgName: "publicPark",
    landscapeValue: 2.5,
    businessValue: 0,
    publicValue: 5,
    minus: [],
    modelType: "x_2",
  },
  {
    bldgName: "communityComplex",
    landscapeValue: 0.5,
    businessValue: 1.5,
    publicValue: 5,
    minus: [],
    modelType: "d_1",
  },
  {
    bldgName: "apartmentBuilding",
    landscapeValue: 1,
    businessValue: 5,
    publicValue: 1,
    minus: ["high", "north"],
    modelType: "y_2",
  },
  {
    bldgName: "officeBuilding",
    landscapeValue: 1,
    businessValue: 4.5,
    publicValue: 1.5,
    minus: ["high", "south"],
    modelType: "y_2",
  },
  {
    bldgName: "uamCenter",
    landscapeValue: 1,
    businessValue: 2,
    publicValue: 4,
    minus: [],
    modelType: "c_1",
  },
  {
    bldgName: "automatedGreenhouse",
    landscapeValue: 0.5,
    businessValue: 4,
    publicValue: 2.5,
    minus: [],
    modelType: "d_1",
  },
  {
    bldgName: "dataCenter",
    landscapeValue: 1,
    businessValue: 3.5,
    publicValue: 3.0,
    minus: [],
    modelType: "y_1",
  },
];
