export const region_data_table = [
  {
    name: 1,
    elevation: "low",
    direction: "south",
    factor: "none",
  },
  {
    name: 2,
    elevation: "low",
    direction: "south",
    factor: "none",
  },
  {
    name: 3,
    elevation: "low",
    direction: "south",
    factor: "none",
  },
  {
    name: 4,
    elevation: "low",
    direction: "north",
    factor: "public",
  },
  {
    name: 5,
    elevation: "low",
    direction: "north",
    factor: "public",
  },
  {
    name: 6,
    elevation: "low",
    direction: "north",
    factor: "landscape",
  },
  {
    name: 7,
    elevation: "low",
    direction: "north",
    factor: "none",
  },
  {
    name: 8,
    elevation: "low",
    direction: "south",
    factor: "none",
  },
  {
    name: 9,
    elevation: "low",
    direction: "south",
    factor: "landscape",
  },
  {
    name: 10,
    elevation: "low",
    direction: "south",
    factor: "public",
  },
  {
    name: 11,
    elevation: "high",
    direction: "south",
    factor: "landscape",
  },
  {
    name: 12,
    elevation: "high",
    direction: "south",
    factor: "none",
  },
  {
    name: 13,
    elevation: "high",
    direction: "north",
    factor: "none",
  },
  {
    name: 14,
    elevation: "high",
    direction: "north",
    factor: "none",
  },
  {
    name: 15,
    elevation: "high",
    direction: "north",
    factor: "landscape",
  },
  {
    name: 16,
    elevation: "high",
    direction: "north",
    factor: "none",
  },
  {
    name: 17,
    elevation: "high",
    direction: "south",
    factor: "none",
  },
  {
    name: 18,
    elevation: "high",
    direction: "south",
    factor: "public",
  },
];
